# -*- coding: utf-8 -*-
"""Text Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vVBZNX3JOwWYN7b_2pJdaEel4-sZemlw
"""

#Importing Required Libraries
import pandas as pd
import requests
from bs4 import BeautifulSoup
import os
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from textblob import TextBlob

# Download the Natural Langauge Took Kit resources
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('cmudict')

# To extract article text from a given URL
# Using BeautifulSoup
def extract_article_text(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, 'html.parser')
        title = soup.find('title').get_text().strip()
        article_text = ''
        for paragraph in soup.find_all('p'):
            article_text += paragraph.get_text().strip() + '\n'
        return title, article_text
    except Exception as e:
        print(f"Error occurred while extracting text from {url}: {e}")
        return None, None

# Function to calculate POSITIVE SCORE, NEGATIVE SCORE, POLARITY SCORE, SUBJECTIVITY SCORE, AVG SENTENCE LENGTH, PERSONAL PRONOUNS, AVG WORD LENGTH
# Function to calculate PERCENTAGE OF COMPLEX WORDS, AVG NUMBER OF WORDS PER SENTENCE, COMPLEX WORD COUNT, calculate WORD COUNT, SYLLABLE PER WORD, AVG WORD LENGTH
def calculate_sentiment_scores(text):
    blob = TextBlob(text)
    positive_score = sum(1 for sentence in blob.sentences if sentence.sentiment.polarity > 0)
    negative_score = sum(1 for sentence in blob.sentences if sentence.sentiment.polarity < 0)
    return positive_score, negative_score
def calculate_polarity_subjectivity(text):
    blob = TextBlob(text)
    polarity_score = blob.sentiment.polarity
    subjectivity_score = blob.sentiment.subjectivity
    return polarity_score, subjectivity_score
def calculate_avg_sentence_length(text):
    sentences = sent_tokenize(text)
    total_words = sum(len(word_tokenize(sentence)) for sentence in sentences)
    return total_words / len(sentences)
def calculate_percentage_complex_words(text):
    words = word_tokenize(text)
    complex_words = [word for word in words if len(word) > 6]
    return (len(complex_words) / len(words)) * 100 if len(words) > 0 else 0
def calculate_fog_index(avg_sentence_length, percentage_complex_words):
    return 0.4 * (avg_sentence_length + percentage_complex_words)
def calculate_avg_words_per_sentence(text):
    words_per_sentence = [len(word_tokenize(sentence)) for sentence in sent_tokenize(text)]
    return sum(words_per_sentence) / len(words_per_sentence) if len(words_per_sentence) > 0 else 0
def calculate_complex_word_count(text):
    words = word_tokenize(text)
    complex_words = [word for word in words if len(word) > 6]
    return len(complex_words)
def calculate_word_count(text):
    words = word_tokenize(text)
    return len(words)
def calculate_syllable_per_word(text):
    d = nltk.corpus.cmudict.dict()
    syllable_count = 0
    word_count = 0
    for word in word_tokenize(text):
        word_count += 1
        if word.lower() in d:
            syllable_count += max([len(list(y for y in x if y[-1].isdigit())) for x in d[word.lower()]])
    return syllable_count / word_count if word_count > 0 else 0
def calculate_personal_pronouns(text):
    personal_pronouns = ['i', 'me', 'my', 'mine', 'myself', 'we', 'us', 'our', 'ours', 'ourselves']
    words = word_tokenize(text.lower())
    personal_pronoun_count = sum(1 for word in words if word in personal_pronouns)
    return personal_pronoun_count
def calculate_avg_word_length(text):
    words = word_tokenize(text)
    word_lengths = [len(word) for word in words]
    return sum(word_lengths) / len(word_lengths) if len(word_lengths) > 0 else 0

# Importing the excel file having URLs
input_df = pd.read_excel("/content/Input.xlsx")
output_directory = "Extracted_Articles"
if not os.path.exists(output_directory):
    os.makedirs(output_directory)

# Creating the Output excel file columns (DataFrame)
output_df = pd.DataFrame(columns=[
    "URL_ID", "TITLE", "POSITIVE SCORE", "NEGATIVE SCORE",
    "POLARITY SCORE", "SUBJECTIVITY SCORE", "AVG SENTENCE LENGTH",
    "PERCENTAGE OF COMPLEX WORDS", "FOG INDEX", "AVG NUMBER OF WORDS PER SENTENCE",
    "COMPLEX WORD COUNT", "WORD COUNT", "SYLLABLE PER WORD",
    "PERSONAL PRONOUNS", "AVG WORD LENGTH"
])

# Extract article text and Save extracted text to a text file
for index, row in input_df.iterrows():
    url_id = row['URL_ID']
    url = row['URL']
    title, article_text = extract_article_text(url)
    if title and article_text:
        output_filename = f"{output_directory}/{url_id}.txt"
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write(title + '\n\n')
            f.write(article_text)
        # Calculating all the parameters
        positive_score, negative_score = calculate_sentiment_scores(article_text)
        polarity_score, subjectivity_score = calculate_polarity_subjectivity(article_text)
        avg_sentence_length = calculate_avg_sentence_length(article_text)
        percentage_complex_words = calculate_percentage_complex_words(article_text)
        fog_index = calculate_fog_index(avg_sentence_length, percentage_complex_words)
        avg_words_per_sentence = calculate_avg_words_per_sentence(article_text)
        complex_word_count = calculate_complex_word_count(article_text)
        word_count = calculate_word_count(article_text)
        syllable_per_word = calculate_syllable_per_word(article_text)
        personal_pronouns = calculate_personal_pronouns(article_text)
        avg_word_length = calculate_avg_word_length(article_text)

        output_df = output_df.append({
            "URL_ID": url_id,
            "TITLE": title,
            "POSITIVE SCORE": positive_score,
            "NEGATIVE SCORE": negative_score,
            "POLARITY SCORE": polarity_score,
            "SUBJECTIVITY SCORE": subjectivity_score,
            "AVG SENTENCE LENGTH": avg_sentence_length,
            "PERCENTAGE OF COMPLEX WORDS": percentage_complex_words,
            "FOG INDEX": fog_index,
            "AVG NUMBER OF WORDS PER SENTENCE": avg_words_per_sentence,
            "COMPLEX WORD COUNT": complex_word_count,
            "WORD COUNT": word_count,
            "SYLLABLE PER WORD": syllable_per_word,
            "PERSONAL PRONOUNS": personal_pronouns,
            "AVG WORD LENGTH": avg_word_length
        }, ignore_index=True)
        print(f"Article extracted from {url} and saved as {output_filename}")
    else:
        print(f"Failed to extract article from {url}")

# Output File in Excel format
output_excel_file = "Output.xlsx"
output_df.to_excel(output_excel_file, index=False)
print(f"Output saved to {output_excel_file}")

